---

- name: Pre-reqs for ansible to run
  hosts: all
  gather_facts: false
  become: yes
  pre_tasks:
    - raw: test -e /usr/bin/python || ( yum -y update && yum install -y python-minimal)

- name: Transfer and execute HAProxy install script.
  hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
    - yum: name=gcc
    - yum: name=pcre-devel
    - yum: name=openssl-devel
    - yum: name=zlib-devel
    - yum: name=wget
    - yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    -  yum: name=python-pip

    - name: Install AWSCLI
      pip: name=awscli


    - name: Get haproxy
      unarchive:
        src: http://www.haproxy.org/download/1.7/src/haproxy-1.7.9.tar.gz
        dest: /usr/src/
        creates: /usr/src/haproxy-1.7.9
        remote_src: yes

    - name: Make haproxy
      make:
        chdir: /usr/src/haproxy-1.7.9
        params:
          TARGET: linux2628
          USE_PCRE: 1
          USE_OPENSSL: 1
          USE_ZLIB: 1
          USE_LIBCRYPT: 1

    - name: Install haproxy
      make:
        chdir: /usr/src/haproxy-1.7.9
        target: install

    - copy:
        remote_src: yes
        src: /usr/src/haproxy-1.7.9/examples/haproxy.init
        dest: /etc/init.d/haproxy
        mode: 0755

    - file:
        src: /usr/local/sbin/haproxy
        dest: /usr/sbin/haproxy
        state: link

    - file:
        path: /etc/haproxy
        state: directory

    - copy:
        src: templates/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg

    - file:
        path: /var/lib/haproxy
        state: directory

    - file:
        path: /var/lib/haproxy/stats
        state: touch

    - systemd: daemon_reload=yes

    - user:
        name: haproxy

    - service:
        name: haproxy
        enabled: yes
        state: started


    - name: Transfer the script
      copy: src=templates/gets3content.sh dest=/home/ec2-user mode=0777

    - name: Test haproxy is running and listening
      shell: echo test >/dev/tcp/localhost/23

    - name: Copy HAProxy config from S3
      cron:
        minute: "*"
        hour: "*"
        job: /home/ec2-user/gets3content.sh
